apps/gridportal/base/Grid/.macros/page/ecos/1_ecos.py, apps/gridportal/base/Grid/.macros/wiki/alert/1_alert.py, apps/gridportal/base/Grid/.macros/wiki/audit/1_audit.py, apps/gridportal/base/Grid/.macros/wiki/eco/1_eco.py, apps/gridportal/base/Grid/.macros/wiki/eventgauge/1_eventgauge.py, apps/gridportal/base/system__gridmanager/methodclass/system_gridmanager.py, apps/portalbase/system/system__errorconditionhandler/methodclass/system_errorconditionhandler.py
Replacing ID with GUID for audit macro
=> Renaming Errorcondition model calls to match new name.

apps/gridportal/base/Grid/.macros/page/ecos/1_ecos.py
issue https://github.com/Jumpscale/jumpscale_portal8/issues/30
=> escapes html in error message

apps/portalbase/system/system__oauth/methodclass/system_oauth.py, lib/portal/portal/PortalRest.py
the portal reset logger category is very unclear any input on what it should be would be appriciated
=> using new loggin system in portal

apps/gridportal/base/Cockpit/.macros/wiki/dockerhosts/3_dockerhosts.py, apps/gridportal/base/Cockpit/.macros/wiki/dockers/3_dockers.py
=> hardening docker macro and dockerhosts macro

apps/gridportal/base/Cockpit/.macros/wiki/aysblueprints/3_aysblueprints.py, apps/portalbase/macros/page/code/1_code_macro.py, jslib/codemirror/autorefresh.js, lib/portal/docgenerator/PageHTML.py
Fixes #46 which should close https://github.com/gig-projects/org_development/issues/233
=> Fixes loading of codemirror with bootstrap

apps/portalbase/macros/wiki/accessdeniedmsg/1_main.py, apps/portalbase/system/system__oauth/methodclass/system_oauth.py, apps/portalbase/wiki/System/AccessDenied/AccessDenied.wiki, lib/portal/portal/MongoEngineBeaker.py, lib/portal/portal/PageProcessor.py
Solves: https://github.com/Jumpscale/jumpscale_portal8/issues/58
=> Improveautherror

apps/gridportal/base/Cockpit/.macros/wiki/aysinstance/3_aysinstance.py, apps/gridportal/base/Cockpit/.macros/wiki/aystemplate/3_aystemplate.py, apps/gridportal/base/Cockpit/AYSInstances/AYSInstance.wiki, apps/gridportal/base/Cockpit/AYSTemplates/AYSTemplate.wiki, apps/portalbase/macros/page/explorer/1_main.py
see : https://github.com/Jumpscale/jscockpit/issues/25
=> show files in code block + add explorer for service instance

apps/gridportal/base/Cockpit/.macros/wiki/aysinstance/3_aysinstance.py, apps/gridportal/base/Cockpit/.macros/wiki/aysinstances/3_aysinstances.py, apps/gridportal/base/Cockpit/.macros/wiki/aystemplate/3_aystemplate.py, apps/gridportal/base/Cockpit/.macros/wiki/aystemplates/3_aystemplates.py, apps/gridportal/base/Cockpit/AYSInstances/AYSInstance.wiki, apps/gridportal/base/Cockpit/AYSInstances/AYSInstances.wiki, apps/gridportal/base/Cockpit/AYSTemplates/AYSTemplate.wiki, apps/portalbase/macros/page/explorer/1_main.py
see : https://github.com/Jumpscale/jscockpit/issues/24
=> Use grid macro instead of simple list

apps/gridportal/base/Cockpit/.macros/wiki/cockpitinfo/3_cockpitinfo.py, apps/gridportal/base/Cockpit/AYSRepos/AYSRepos.wiki, apps/gridportal/base/Cockpit/Information/Information.wiki, apps/gridportal/base/system__atyourservice/methodclass/system_atyourservice.py, apps/gridportal/base/system__atyourservice/specs/actor.spec
relates to : 
https://github.com/Jumpscale/jumpscale_portal8/pull/66
https://github.com/Jumpscale/jscockpit/issues/26
=> implement commit of cockpit repo from portal actions

apps/portalbase/system/system__atyourservice/methodclass/system_atyourservice.py
Fix issue where cockpit client uses a global client not specific to
user of the request.
Store jwttoken on the user session and validate from there.
=> Add jwt token in session and validate from there

lib/portal/portal/exceptions.py
add method to create Exception class from status code
=> For story Cockpit beta

apps/portalbase/macros/page/accordion/3_accordion.py, lib/portal/portal/exceptions.py
=> Cockpit beta

apps/portalbase/AYS81/Repos/Repo.wiki, apps/portalbase/macros/page/form/3_form.py, apps/portalbase/system/system__atyourservice/methodclass/system_atyourservice.py, apps/portalbase/system/system__atyourservice/specs/actor.spec, jslib/flatui/css/flat-ui.css, lib/portal/docgenerator/form.py, lib/portal/docgenerator/popup.py
See https://github.com/Jumpscale/jscockpit/issues/287
=> form for quickly demoing blueprints

apps/portalbase/AYS81/.macros/wiki/repoversion/3_repoversion.py
Signed-off-by: Ashraf Fouda <foudaa@greenitglobe.com>
=> Adds get the versions from flist if exists

apps/portalbase/AYS81/.macros/page/aysjobprofile/3_aysjobprofile.py
Fixes for handling the HTTP_HOST instead of using localhost/SERVERNAME 
Doesn't address proxying issue.
=> Portal 293

apps/portalbase/AYS81/JWT/jwt.wiki, apps/portalbase/system/system__oauth/methodclass/system_oauth.py, apps/portalbase/system/system__oauthtoken/methodclass/system_oauthtoken.py, apps/portalbase/system/system__oauthtoken/specs/actor.spec
=> Get a jwt token instead of oauth2 token to be able to support refreshing

apps/portalbase/AYS81/.macros/wiki/repoversion/3_repoversion.py
Signed-off-by: Ashraf Fouda <foudaa@greenitglobe.com>
=> Adds fix to version page to not freeze

apps/portalbase/AYS81/Runs/Runs.wiki, apps/portalbase/system/system__atyourservice/methodclass/system_atyourservice.py, apps/portalbase/system/system__atyourservice/specs/actor.spec
=> Jscockpit actiontoremoveallruns 303

apps/portalbase/macros/page/serverlocation/5_serverlocation.py, jslib/ipmapper.js
Signed-off-by: Ashraf Fouda <foudaa@greenitglobe.com>
=> Fixes server info page not loading

apps/portalbase/macros/page/serverlocation/5_serverlocation.py
Signed-off-by: Ashraf Fouda <foudaa@greenitglobe.com>
=> Adds google api key for serverinfo page

lib/portal/html/elFinder.py
relates to issue https://github.com/Jumpscale/jscockpit/issues/295
=> bug fix concerning hanging elfinder explorer

apps/portalbase/AYS81/.macros/wiki/actortemplates/3_actortemplates.py, apps/portalbase/AYS81/.macros/wiki/aysblueprints/3_aysblueprints.py, apps/portalbase/AYS81/.macros/wiki/aysjob/3_aysjob.py, apps/portalbase/AYS81/.macros/wiki/aysrepo/3_aysrepo.py, apps/portalbase/AYS81/.macros/wiki/aysrun/3_aysrun.py, apps/portalbase/AYS81/.macros/wiki/aysruns/3_aysruns.py, apps/portalbase/AYS81/.macros/wiki/aysservice/3_aysservice.py, apps/portalbase/AYS81/.macros/wiki/aysservices/3_aysservices.py, apps/portalbase/AYS81/.macros/wiki/repoversion/3_repoversion.py, apps/portalbase/AYS81/Details/ActorTemplate.wiki, apps/portalbase/AYS81/Details/ActorTemplates.wiki, apps/portalbase/AYS81/Details/Blueprints/Blueprints.wiki, apps/portalbase/AYS81/Details/Explorer.wiki, apps/portalbase/AYS81/Details/Service.wiki, apps/portalbase/AYS81/Details/Services.wiki, apps/portalbase/AYS81/Repos/Repo.wiki, apps/portalbase/AYS81/Repos/Repos.wiki, apps/portalbase/AYS81/Repos/Simulate.wiki, apps/portalbase/AYS81/Runs/Job.wiki, apps/portalbase/AYS81/Runs/RunModel.wiki, apps/portalbase/AYS81/Runs/Runs.wiki, apps/portalbase/macros/wiki/hardenwiki/3_hardenwiki.py, apps/portalbase/macros/wiki/kanbandata/3_kanbandata.py, lib/portal/docgenerator/PageHTML.py, tags
this relates to :
- #120
- #118
=> added macro hardenwiki + hadnled some errors on ays macros

apps/portalbase/system/system__atyourservice/methodclass/system_atyourservice.py, apps/portalbase/system/system__atyourservice/specs/actor.spec, apps/portalbase/system/system__contentmanager/methodclass/system_contentmanager.py, apps/portalbase/system/system__contentmanager/specs/actor.spec, apps/portalbase/system/system__usermanager/methodclass/system_usermanager.py
Fixes for https://github.com/Jumpscale/jscockpit/issues/373
=> Fixesforwrongexecptions

apps/portalbase/AYS81/.macros/wiki/actortemplates/3_actortemplates.py, apps/portalbase/AYS81/.macros/wiki/aysactor/3_aysactor.py, apps/portalbase/AYS81/.macros/wiki/aysactors/3_aysactors.py, apps/portalbase/AYS81/.macros/wiki/aysactortemplate/3_aysactortemplate.py, apps/portalbase/AYS81/.macros/wiki/aysblueprints/3_aysblueprints.py, apps/portalbase/AYS81/.macros/wiki/aysjob/3_aysjob.py, apps/portalbase/AYS81/.macros/wiki/aysrepo/3_aysrepo.py, apps/portalbase/AYS81/.macros/wiki/aysrepos/3_aysrepos.py, apps/portalbase/AYS81/.macros/wiki/aysrun/3_aysrun.py, apps/portalbase/AYS81/.macros/wiki/aysruns/3_aysruns.py, apps/portalbase/AYS81/.macros/wiki/aysservice/3_aysservice.py, apps/portalbase/AYS81/.macros/wiki/aysservices/3_aysservices.py, apps/portalbase/AYS81/.macros/wiki/ayssimulatorresult/3_ayssimulatorresult.py, apps/portalbase/AYS81/.macros/wiki/repoexists/3_repoexists.py, apps/portalbase/AYS81/Actors/Actor.wiki, apps/portalbase/AYS81/Actors/Actors.wiki, apps/portalbase/AYS81/Details/ActorTemplate.wiki, apps/portalbase/AYS81/Details/ActorTemplates.wiki, apps/portalbase/AYS81/Details/Blueprints/Blueprints.wiki, apps/portalbase/AYS81/Details/Service.wiki, apps/portalbase/AYS81/Details/Services.wiki, apps/portalbase/AYS81/Repos/Repo.wiki, apps/portalbase/AYS81/Repos/Repos.wiki, apps/portalbase/AYS81/Repos/Simulate.wiki, apps/portalbase/AYS81/Runs/Job.wiki, apps/portalbase/AYS81/Runs/RunModel.wiki, apps/portalbase/AYS81/Runs/Runs.wiki, apps/portalbase/system/system__atyourservice/methodclass/system_atyourservice.py, apps/portalbase/system/system__atyourservice/specs/actor.spec
WIP make most of the macros use the atyourservice client
=> Portal cleanup 149
